### ISSUE TITLE
大神能不能给个使用教程，我是小白

### ISSUE THREAD

**Issue by Huanglongchun** [GeneCaoHQ/SSAccountAutoGet#1]

**Comment by Huanglongchun** [comment]
^_^ 欢迎使用SS账号自动获取器，祝生活愉快！ ^_^
Exception in thread Thread-1:
Traceback (most recent call last):
  File "G:\python2.7\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "G:\python2.7\lib\threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "SSAccountAutoGet.py", line 108, in get_last_pw
    autoModifyPW(extractHtml(login(form_data)))
  File "SSAccountAutoGet.py", line 95, in login
    response = s.post(url_login, data = form_data, headers = header)
  File "G:\python2.7\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "G:\python2.7\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\python2.7\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "G:\python2.7\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='www.ss-link.com', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000438E0F0>: Failed to establish a new connection: [Errno 11003] getaddrinfo failed',))

这个怎么办？

**Comment by Jcdroid** [comment]
ConnectionError: HTTPSConnectionPool(host='www.ss-link.com', port=443)，www.ss-link.com这个地址已经关停了，你可以再找找有没有类似的网站 😅

**Comment by GeneCaoHQ** [comment]
@Huanglongchun `ConnectionError: HTTPSConnectionPool(host='www.ss-link.com', port=443)，www.ss-link.com`这个地址已经关停了，你可以再找找有没有类似的网站 😅

**Comment by Huanglongchun** [comment]
能麻烦你帮我配置一下这个网址吗https://my.ishadowx.net/，对python一窍不通。
